#pragma once

#ifndef KEYBOARDCONTROLS_H
#define KEYBOARDCONTROLS_H

enum KeyboardControls {
	KEY_PRESS_DOWN,
	KEY_PRESS_UP,
	KEY_PRESS_RIGHT,
	KEY_PRESS_LEFT,
	KEY_PRESS_LATK1,
	KEY_PRESS_MATK1,
	KEY_PRESS_HATK1,
	KEY_PRESS_LATK2,
	KEY_PRESS_MATK2,
	KEY_PRESS_HATK3
};

#endif KEYBOARDCONTROLS_H